/**
 * Maestro de sellers 3P de Carrefour Argentina. Fuente de verdad para
 * elegir qué sellerIds trackear en el cron nocturno (ver
 * .github/workflows/fetch-catalog.yml → DEFAULT_SELLER_IDS).
 *
 * No todo este listado corre nightly: DEFAULT_SELLER_IDS empieza con un
 * subset chico para validar el pipeline end-to-end antes de escalar al
 * resto. Para sumar un seller al cron, agregá su `id` a esa variable del
 * workflow.
 */
export const MAESTRO_SELLERS = [
  { id: "abaco284", name: "Abaco" },
  { id: "aircomputers546", name: "Advantec" },
  { id: "americanwood705", name: "American Wood" },
  { id: "anubisdecoracion261", name: "Anubis" },
  { id: "Autodo", name: "Autodo" },
  { id: "awaresolutions923", name: "Seller Aware Solutions" },
  { id: "awaresolutionssrl189", name: "Aware Solutions SRL" },
  { id: "bangho", name: "Bangho" },
  { id: "beautysas", name: "beauty24" },
  { id: "Bebitos", name: "Bebitos" },
  { id: "bigstarsar", name: "bigstarsar" },
  { id: "blackmusic902", name: "Black Music" },
  { id: "brogas700", name: "Brogas" },
  { id: "buhl040", name: "Buhl" },
  { id: "bulonfer", name: "bulonfer" },
  { id: "bydsudamericana031", name: "B Y D Sudamericana" },
  { id: "calefactorescalden943", name: "Calden" },
  { id: "calm328", name: "Calm" },
  { id: "carrelloar624", name: "Carello" },
  { id: "clubdigital656", name: "Club Digital" },
  { id: "codini088", name: "CODINI" },
  { id: "colchonesysommier288", name: "Colchones&Sommiers 2230" },
  { id: "CRF", name: "Bangho" },
  { id: "ctcgroup940", name: "CTC" },
  { id: "ctcproductos740", name: "CTC Productos" },
  { id: "dehuka404", name: "Dehuka" },
  { id: "demelf394", name: "Demelf" },
  { id: "derpacomar064", name: "Simpel" },
  { id: "dielfe771", name: "Dielfe" },
  { id: "districolor768", name: "Districolor" },
  { id: "districolor804", name: "Instax" },
  { id: "donacero930", name: "Don Acero" },
  { id: "dvigi943", name: "Dvigi" },
  { id: "eczanepharma170", name: "SacuDigital" },
  { id: "electroluxar", name: "Electrolux" },
  { id: "emcmuebles005", name: "EMC Muebles" },
  { id: "emoodmarket", name: "Emood" },
  { id: "enasport189", name: "Ena Sports" },
  { id: "estelar454", name: "Estelar" },
  { id: "exosa541", name: "Exo" },
  { id: "ferreydeco793", name: "Ferre y Deco" },
  { id: "gasei472", name: "Gasei" },
  { id: "grupomarquez012", name: "Grupo Marquez" },
  { id: "haustore986", name: "Haustore" },
  { id: "hidrolit736", name: "Hidrolit" },
  { id: "hispanos470", name: "5 Hispanos" },
  { id: "hogarisnova327", name: "Hogaris Nova" },
  { id: "homekong441", name: "Home Kong" },
  { id: "intecnova657", name: "Intecnova" },
  { id: "internationalhomesa717", name: "International Home SA" },
  { id: "kamadoargentino563", name: "Kamado" },
  { id: "kiluga771", name: "Kiluga" },
  { id: "kitsolar316", name: "Kit Solar" },
  { id: "laplanchetta301", name: "La planchetta" },
  { id: "lilasense516", name: "Lilasense" },
  { id: "limansky653", name: "Colchones y Sommiers" },
  { id: "lumina946", name: "Lumina" },
  { id: "luxom345", name: "Luxom" },
  { id: "magazzinoar", name: "Magazzino" },
  { id: "mantra171", name: "Mantra" },
  { id: "mgsolucionsa519", name: "Grill Gloves" },
  { id: "microbell122", name: "microbell" },
  { id: "mueblesespeciales315", name: "Muebles especiales" },
  { id: "mundopino165", name: "Mundo Pino" },
  { id: "neba791", name: "NEBA" },
  { id: "neoseg957", name: "Neoseg" },
  { id: "ohgiftcard537", name: "Oh giftcard" },
  { id: "ortopedialibertad288", name: "Ortopedia Libertad" },
  { id: "outin691", name: "Outin" },
  { id: "pampadeacero948", name: "Pampa de Acero" },
  { id: "phidigital143", name: "Phi-digital" },
  { id: "pinataar", name: "Piñata" },
  { id: "pinataarCRF", name: "pinataar" },
  { id: "potenzaemarketsa179", name: "Potenza" },
  { id: "praga278", name: "Praga" },
  { id: "prestigio1", name: "Prestigio" },
  { id: "Producteca225119", name: "DMAKER S.A." },
  { id: "Producteca232302", name: "Etercor" },
  { id: "Producteca232621", name: "ARGENTRADE S R L .-" },
  { id: "Producteca237680", name: "Cooking Store" },
  { id: "Producteca238451", name: "Multipoint" },
  { id: "Producteca238567", name: "Decohogar" },
  { id: "Producteca238818", name: "BGH" },
  { id: "Producteca239254", name: "Sony" },
  { id: "Producteca241872", name: "Kronen" },
  { id: "Producteca241968", name: "Newsan" },
  { id: "Producteca242766", name: "Pilisar" },
  { id: "Producteca246251", name: "Florencia Cortes MIX MATCH" },
  { id: "Producteca246437", name: "Drean SA" },
  { id: "Producteca246519", name: "Visuar" },
  { id: "Producteca246643", name: "Sueño Dorado" },
  { id: "Producteca247492", name: "Grupo Nucleo" },
  { id: "Producteca247683", name: "Bidcom" },
  { id: "Producteca249023", name: "Tomas Berciotti MORANO MAQUINAS Y HERRAMIENTAS" },
  { id: "Producteca249357", name: "HOUSE & OFFICE" },
  { id: "Producteca249773", name: "GreenDeco" },
  { id: "Producteca251086", name: "Distrillantas" },
  { id: "Producteca251428", name: "Juan Duran Trendy Deals" },
  { id: "Producteca252062", name: "Novatech" },
  { id: "Producteca70438", name: "TecnoB" },
  { id: "puntodeportivoar", name: "Punto Deportivo" },
  { id: "rockinroll106", name: "Rock in Roll" },
  { id: "rua839", name: "Rua" },
  { id: "sccortinasrollers240", name: "SC Cortinas Rollers" },
  { id: "sharecomputacion867", name: "Share Computacion" },
  { id: "shopwide119", name: "Shop Wide" },
  { id: "soportar561", name: "SOPORT" },
  { id: "springwall441", name: "Springwall" },
  { id: "sungreensrl102", name: "Sungreen" },
  { id: "tecnofull391", name: "Tecnoshop" },
  { id: "tenacta582", name: "Tenacta" },
  { id: "tiendasdigitalesar", name: "Tidi" },
  { id: "todotodo061", name: "TodoTodo" },
  { id: "topmega421", name: "Top Mega" },
  { id: "turboblender168", name: "Turboblender" },
  { id: "tutiendaonline271", name: "TutiendaOnline" },
  { id: "unitecsa564", name: "Unitec S.A." },
  { id: "universopinturerias", name: "Universo pinturerias" },
  { id: "Vexi", name: "vexistorear" },
  { id: "vexistore751", name: "Vexi Store" },
  { id: "vexistorear", name: "Vexi" },
  { id: "vinson363", name: "Vinson" },
  { id: "vmpsa473", name: "Vmpsa" },
  { id: "whirlpoolarg", name: "WHIRLPOOL S.A" },
  { id: "wolke303", name: "Wolke" },
  { id: "wsabiskin470", name: "WSabi" },
  { id: "xcientoargentino189", name: "Argentino" },
] as const;

export const MAESTRO_SELLER_SET: Set<string> = new Set(MAESTRO_SELLERS.map((s) => s.id));
